package pqt.dss.cor.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 12 11:40:28 PKT 2016
// ---------------------------------------------------------------------
public interface DssCorHeaderView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);

    void corSearchUser();
}

