package pqt.dss.cor.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 30 15:15:44 PKT 2016
// ---------------------------------------------------------------------
public interface CORAM extends ApplicationModule {
    void Apply();

    void Delete();

    void Rollback();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    void DssApprove();

    String searchAgents();

    void callCORWorkflow(oracle.jbo.domain.Number p_document_id);
}

